modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "mobbiscuits"
version = "${version}"
displayName = "Mob Biscuits"
authors = "ElectricSteve"
description = '''
A mod that adds biscuits (cookies if you prefer) with mob faces.
'''
logoFile = "assets/mobbiscuits/icon.png"
updateJSONURL = "https://api.modrinth.com/updates/mobbiscuits/forge_updates.json"
modUrl = "https://modrinth.com/mod/mobbiscuits"
displayURL = "https://modrinth.com/mod/mobbiscuits"

[[dependencies.mobbiscuits]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mobbiscuits]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.8,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mobbiscuits]]
modId = "architectury"
type = "required"
versionRange = "[17.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "mobbiscuits.mixins.json"

[[mixins]]
config = "mobbiscuits.neoforge.mixins.json"